language: rust
os: linux
dist: xenial

addons:
  apt:
    packages:
#   - graphviz

cache:
  - cargo
  - apt: true

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4.7" mdbook)
# - (test -x $HOME/.cargo/bin/mdbook-graphviz || cargo install --vers "^0.0.2" mdbook-graphviz)
  - cargo install-update -a

script:
  - mdbook build $HOME/build/Albus/BssDocs && mdbook test $HOME/build/Albus/BssDocs
  
deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: $HOME/build/Albus/BssDocs/book
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages