[book]
authors = ["Антон Растяженко"]
language = "ru"
multilingual = false
src = "src"
title = "Документация SBS"

[output.html.print]
enable = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = false
copy-fonts = true
git-repository-url = "https://github.com/Albus/BssDocs"
git-repository-icon = "fa-github"
additional-js = ["src/custom.js"]


